###
 # THIS FILE IS AUTOMATICALLY GENERATED
 # Do not edit this file. It will be overwritten when the configure script is run.
###

######
# Build ID: 33d8f33196c9017d
# Executable: ./bin/champsim_36core
# Module Names: ('btbDbasic_btb', 'branchDbimodal', 'branchDgshare', 'branchDhashed_perceptron', 'branchDperceptron', 'prefetcherDip_stride', 'prefetcherDnext_line', 'prefetcherDno', 'prefetcherDschedule_pf', 'prefetcherDspp_dev', 'prefetcherDtile_aware_amx', 'prefetcherDva_ampm_lite', 'replacementDdrrip', 'replacementDlru', 'replacementDrandom', 'replacementDship', 'replacementDsrrip')
######

BIN_ROOT := bin
compile_commands $(BIN_ROOT)/champsim_36core: build_id := \
  33d8f33196c9017d
nonbase_module_objs += $(filter-out $(base_module_objs),$(call get_module_list, btb/basic_btb \
  branch/bimodal branch/gshare branch/hashed_perceptron \
  branch/perceptron prefetcher/ip_stride prefetcher/next_line \
  prefetcher/no prefetcher/schedule_pf prefetcher/spp_dev \
  prefetcher/tile_aware_amx prefetcher/va_ampm_lite replacement/drrip \
  replacement/lru replacement/random replacement/ship \
  replacement/srrip ))
build_ids += 33d8f33196c9017d
executable_name += $(BIN_ROOT)/champsim_36core
